version: "3.8"
services:
  web_ci4:
    build: src/app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:rw

  db_ci4:
    build: dockerfiles/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=docker_database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    volumes:
      - ./database:/var/lib/mysql:ro
      # - ./docker/logs/mysql:/var/log/mysql
      
  phpmyadmin:
    image: phpmyadmin
    links:
      - db_ci4
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
