version: "3.8"
services:
  web_ci4:
    container_name: web_ci4_cus
    image: web-ci4-cus-image:v1.0.1
    build: src/app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:rw

  db_ci4:
    container_name: mysql_db_ci4_cus
    image: mysql-db-cus-image:latest
    build: dockerfiles/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=docker_database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    volumes:
      - ./database:/var/lib/mysql:rw
      # - ./docker/logs/mysql:/var/log/mysql
     
  phpmyadmin:
    container_name: my_phpmyadmin_container
    image: phpmyadmin
    links:
      - db_ci4
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80

volumes:
  databse:
  src:
  db-logs:
  apache-cus-conf-backup:
